Feature webapi
htl-grieskirchen-core/plugin-quote-of-today pull request #1
Opened 2022-12-12 08:15 UTC by EinboeckFranz

implements endpoints for quote of today feature

2022-12-12 08:27 UTC, profiluefter commented on CorePlugin.Plugin/Services/QuotesService.cs
> +    }
quote of today ned quote of the second

2022-12-12 08:32 UTC, EinboeckFranz commented on CorePlugin.Plugin/Services/QuotesService.cs
> +    }
öha

2022-12-12 08:37 UTC, profiluefter commented on CorePlugin.Plugin/Services/DatabaseBackgroundService.cs
> +        return Task.Run(() =>
stott task.run konnst de funktion a einfoch async mocha

2022-12-12 08:39 UTC, profiluefter commented on CorePlugin.Plugin/Services/QuotesService.cs
> +            throw new QuoteAlreadyExistsException("Quote already exists");
do muast an text vorm vergleichen trimmen sonst konn i mid leerzeichen den check umgeh und hos donn wieda zwoamoi drin

2022-12-12 08:40 UTC, EinboeckFranz commented on CorePlugin.Plugin/Services/DatabaseBackgroundService.cs
> +        return Task.Run(() =>
wie genau?

2022-12-12 08:42 UTC, profiluefter commented on CorePlugin.Plugin/Controller/QuotesController.cs
> +    public async Task<ActionResult<Quote>> GetRandomQuote()
soid des ned a quote dto wean? und im dto einfoch olles aus da db hätt i gsogt, username und id

2022-12-12 08:42 UTC, EinboeckFranz commented on CorePlugin.Plugin/Services/QuotesService.cs
> +            throw new QuoteAlreadyExistsException("Quote already exists");
![image](https://user-images.githubusercontent.com/71697706/207000118-5db03be6-1c32-49f9-ab80-384bc2ee06f8.png)
Wiad eh beim speichern trimmt

2022-12-12 08:43 UTC, EinboeckFranz commented on CorePlugin.Plugin/Controller/QuotesController.cs
> +    public async Task<ActionResult<Quote>> GetRandomQuote()
najo des dto is einfoch da quote text den da user herschickt, und a quote gib i einfoch zruck

2022-12-12 08:45 UTC, profiluefter commented on CorePlugin.Plugin/Services/DatabaseBackgroundService.cs
> +        return Task.Run(() =>
`protected override async Task Execute...`
und donn einfoch mid await bei de funktionen

2022-12-12 08:48 UTC, profiluefter commented on CorePlugin.Plugin/Services/QuotesService.cs
> +            throw new QuoteAlreadyExistsException("Quote already exists");
jo oba wird ungetrimmt vergleicht
z.b. konn i "spost    " submitten und wonns "spost" scho gibt steht donn zwoamoi "spost" drin trotz dem check

2022-12-12 08:49 UTC, profiluefter commented on CorePlugin.Plugin/Controller/QuotesController.cs
> +    public async Task<ActionResult<Quote>> GetRandomQuote()
aso oiso wird der eh benutzt oba hoid beim submitten, donn hättst oba fost einfoch an string nehma kinna oba vlt erweitert des jo irgendwonn moi wer

2022-12-12 08:51 UTC, profiluefter commented on CorePlugin.Plugin/Services/QuotesService.cs
> +            throw new QuoteAlreadyExistsException("Quote already exists");
von mir aus is' verdraht ok

2022-12-12 08:52 UTC, EinboeckFranz commented on CorePlugin.Plugin/Services/QuotesService.cs
> +            throw new QuoteAlreadyExistsException("Quote already exists");
is resolved, @profiluefter hod se vaschau

2022-12-12 08:57 UTC, profiluefter commented on CorePlugin.Plugin/Services/DatabaseBackgroundService.cs
> +        return Task.Run(() =>
jo genau so moan i

2022-12-12 08:59 UTC, EinboeckFranz commented on CorePlugin.Plugin/Services/DatabaseBackgroundService.cs
> +        return Task.Run(() =>
resolved in https://github.com/htl-grieskirchen-core/plugin-quote-of-today/pull/1/commits/3857d9d3c505fde3bc1ba1a1a2d3c5b01a19269e

2022-12-12 08:59 UTC, EinboeckFranz commented on CorePlugin.Plugin/Services/QuotesService.cs
> +    }
resolved in https://github.com/htl-grieskirchen-core/plugin-quote-of-today/pull/1/commits/3857d9d3c505fde3bc1ba1a1a2d3c5b01a19269e

2022-12-12 09:02 UTC, profiluefter requested changes

2022-12-12 09:02 UTC, profiluefter commented on CorePlugin.Plugin/Services/QuotesService.cs
> +        var count = await _db.Quotes.Where(x => x.SubmitTime.Date == DateTime.Now.Date).CountAsync();
oiso quote of today soid eher a random quote sei der jedn tag da selbe is und ned der an dem tag submitted is

2022-12-12 09:03 UTC, profiluefter commented on CorePlugin.Plugin/Services/QuotesService.cs
> +        var count = await _db.Quotes.Where(x => x.SubmitTime.Date == DateTime.Now.Date).CountAsync();
is nu weng a komplexere soch, vlt schraubn wa do in zukunft eh nu weng umadum

2022-12-12 09:15 UTC, EinboeckFranz commented on CorePlugin.Plugin/Services/QuotesService.cs
> +        var count = await _db.Quotes.Where(x => x.SubmitTime.Date == DateTime.Now.Date).CountAsync();
resolved in https://github.com/htl-grieskirchen-core/plugin-quote-of-today/pull/1/commits/e4b9e899073ca727163394207e4301faf1f45f79

2022-12-12 20:54 UTC, profiluefter requested changes
kloane optimierung nu donn hommas gschofft

2022-12-12 20:54 UTC, profiluefter commented on CorePlugin.Plugin/Services/QuotesService.cs
> +            return _quotesOfDays[DateTime.Now.Date];
should be the first line of the function so we don't need a database call every time

2022-12-13 10:19 UTC, EinboeckFranz commented on CorePlugin.Plugin/Services/QuotesService.cs
> +            return _quotesOfDays[DateTime.Now.Date];
resolved in https://github.com/htl-grieskirchen-core/plugin-quote-of-today/commit/65fe4d15c379bcbfd2d1a03de1844943225e0755

2022-12-15 11:53 UTC, Klausmd5 approved these changes
schaud ok aus

2022-12-15 11:54 UTC, merged